/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package googleassistbot;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

public class App {
    

    public static void main(String[] args) {
    }
}

