/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112807-ge56d91f8a8-20231120"
#endif /* AVUTIL_FFVERSION_H */
